apiVersion: v1
kind: Service
metadata:
  labels:
    app: final
  name: final
spec:
  ports:
  - name: final
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30010
  selector:
    app: final
  type: NodePort
status:
  loadBalancer: {}
